### ISSUE TITLE
sharptimer_max_start_speed

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#10]
sharptimer_max_start_speed is not being applied when changed

**Comment by NordicGamerFE** [comment]
custom_exec.cfg was conflicting with my config.

**Comment by NordicGamerFE** [comment]
Actaully this is still a issue i have

**Comment by rcnoob** [comment]
Can you enable sharptimer debug mode and provide a console log with all personal data removed? Also make sure you edit MapData/MapExecs/surf_.cfg as that also executes on map start

**Comment by NordicGamerFE** [comment]
bhop.cfg was my issue thank you.
