### ISSUE TITLE
Dev Pre-release 0.3.1q bug - Failed to GetSortedRecordsFromGlobal spams server console

### ISSUE THREAD

**Issue by BoTo-sg** [Letaryat/poor-sharptimer#106]
The dev version has a bug where it spams the server console with [SharpTimerERROR] Failed to GetSortedRecordsFromGlobal. Status code: Unauthorized

public async Task<Dictionary<int, PlayerRecord>> GetSortedRecordsFromGlobal(int limit = 0, int bonusX = 0, string mapName = "", int style = 0)

is missing

if (apiKey == "")
      return;

**Comment by rcnoob** [comment]
thank you! will be fixed next update
