### ISSUE TITLE
[Suggestion] No jumping in zones

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#11]
I would love a option to disable jumping within the start zone.

**Comment by rcnoob** [comment]
Would this ideally be map-specific or server-wide?

**Comment by NordicGamerFE** [comment]
Server wide, most of the csgo timers worked like that

**Comment by NordicGamerFE** [comment]
The effect sometimes act weirdy on spawning in, and also gives you a little sliding effect when jumping. 
https://youtu.be/UyP-YA2vA_o

**Comment by NordicGamerFE** [comment]
fixed
