### ISSUE TITLE
[Suggestion] styles

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#14]
I know this is a big task but i would love to see the introduction of !styles
Styles in CSGO was a way to bring more life into the maps by giving the player many options, each style had its own records and replays.
Here is a good place to see what kind of styles there were in csgo
https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/configs/shavit-styles.cfg

**Comment by rcnoob** [comment]
added (somewhat) in 0.2.9f
more will come once as I slowly figure out how to implement them

**Comment by NordicGamerFE** [comment]
04:23:13 [INFO] (plugin:SharpTimer) [SharpTimerERROR] Error getting sorted records from MySQL: Unknown column 'Style' in 'where clause'
04:23:24 [INFO] (plugin:SharpTimer) [SharpTimerERROR] Error saving player time to MySQL: Unknown column 'Style' in 'where clause'

**Comment by NordicGamerFE** [comment]
currently you have to do !styles to see the list and !style to select but the selection name and menu name dont match my suggestion would be to only have !style and a selection list like this 
![image](https://github.com/Letaryat/poor-sharptimer/assets/18188155/0ceddb30-88df-4976-aedb-ad21cf1f6cce)
BTW i tested all the styles and they all seem to work like expected.

**Comment by NordicGamerFE** [comment]
also i looked at the points for styles and they are kinda wack
this is my personal list of what is eaiest to hardest
low gravity (should give less points then normal)
normal
400 vel
high gravity
sideways
onlyw

**Comment by NordicGamerFE** [comment]
> also i looked at the points for styles and they are kinda wack this is my personal list of what is eaiest to hardest low gravity (should give less points then normal) normal 400 vel high gravity sideways onlyw

Honestly the best option would be to make this configrable

**Comment by rcnoob** [comment]
Sadly menus are no longer a thing in cs2, at least in the sense of csgo's menus. There _could_ be a chat menu, but that just results in more commands/spam sent by people who only use ! instead of /

Configuration will be implemented

**Comment by NordicGamerFE** [comment]
webhook currently does not display a style

**Comment by NordicGamerFE** [comment]
i get this error if finish while having a time down from before it works fine if its my first time getting a time 
21:29:11 [INFO] (plugin:SharpTimer) [SharpTimerERROR] Error saving player time to MySQL: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONFLICT (MapName, SteamID, Style)

**Comment by rcnoob** [comment]
fixed both in 0.2.9j

**Comment by NordicGamerFE** [comment]
400vel also does not have normal downwards velocity

**Comment by rcnoob** [comment]
I was wondering about that, i knew it felt too hard. I had no idea if all axes respected the 400vel limit. So Z axis (rising and falling) should be unlocked?

**Comment by NordicGamerFE** [comment]
yeah z axis should be unrestricted also surfing should be unrestricted but I assume that is not possible.

**Comment by rcnoob** [comment]
wait, so 400vel should ONLY be applied in air? never knew that either

**Comment by NordicGamerFE** [comment]
Here is a video if it helps https://www.youtube.com/watch?v=bkf0oGUh4ic

**Comment by NordicGamerFE** [comment]
Also here is the styles from another csgo plugin if it helps you at all https://github.com/blankbhop/btimes/blob/master/addons/sourcemod/configs/timer/styles.cfg

**Comment by rcnoob** [comment]
both somewhat help but im still confused about 400vel due to the video not drawing HUD; i can easily check if a player is in the air however. so should I be setting maxvel to 400 ONLY if player is in air? then on surf/on bhopblock maxvel is unlimited?

**Comment by NordicGamerFE** [comment]
i dont know all the technical stuff behind it, and I never did much 400vel bhop so I dont exactly how it works. but if you do that I could test it and see if it feels correct, and its a new age so if its not exactly the same it does not matter.
