### ISSUE TITLE
[QOF-Suggestion] !timer

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#15]
Currently you have to do !timer when doing a replay but I would imagine its possible to make this logic automatic to where the user does not actually have to do a extra command to enter replay.

**Comment by rcnoob** [comment]
implemented in 0.2.9d

**Comment by NordicGamerFE** [comment]
@rcnoob I just wanna thank you for your hard work, Its nice to see someone who cares enough to make a impact on the cs2 movement community.
