### ISSUE TITLE
[Suggestion] SR/PB Sound events

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#17]
It would be nice if you could configure a sound to play if a player hits a pb or a sr.

**Comment by exkludera** [comment]
[poor-sharptimer/pull/38](https://github.com/Letaryat/poor-sharptimer/pull/38)


![1158638405140365434](https://github.com/Letaryat/poor-sharptimer/assets/51145038/e55c388a-753d-4289-b41c-2b7547707db4)

**Comment by NordicGamerFE** [comment]
![img](https://private-user-images.githubusercontent.com/51145038/344500183-e55c388a-753d-4289-b41c-2b7547707db4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3OTM3MTUsIm5iZiI6MTcxOTc5MzQxNSwicGF0aCI6Ii81MTE0NTAzOC8zNDQ1MDAxODMtZTU1YzM4OGEtNzUzZC00Mjg5LWI0MWMtMmI3NTQ3NzA3ZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYWEzN2RhMWRkNDIzMGNjZDI3ZmE3YmE2ZTE5Y2RmZmQ0MThlOThlNmE0NzEwNjg5NGNkNjExMWVmZDcyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NvLRReid7vREFZ8MiC8__7TKUuddoty9yHaqnThIG4c)

**Comment by NordicGamerFE** [comment]
you should checkout this btw @exkludera you might find out useful https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
