### ISSUE TITLE
[Suggestion] SSJ / SYNC

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#18]
SSJ: i would love to see SSJ integrated into the plugin [SSJ CSGO Plugin](https://forums.alliedmods.net/showthread.php?p=2449592)
SYNC: I've noticed that cybershock has a sync % in their timer I think this is a good idea and something that should come to the plugin.
![image](https://github.com/Letaryat/poor-sharptimer/assets/18188155/f33cbcba-654d-4fa4-998d-5b372bdbde7d)
I also wanna mention I like their timer how they got SR and PB

**Comment by M-archand** [comment]
Jump Stats & Sync features both exist as of [0.3.0](https://github.com/Letaryat/poor-sharptimer/releases/tag/v0.3.0)
