### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#21]
Error Saving Time: Player current checkpoint does not match final one (7)

**Comment by NordicGamerFE** [comment]
this is happening on a map that used to work, the map in question is bhop_at_night_r

**Comment by NordicGamerFE** [comment]
found a way to duplicate the error play a map like bhop_dunedash that has checkpoints buildt into the map then go and play bhop_at_night

**Comment by rcnoob** [comment]
should be fixed in pre-release 0.2.9b; let me know the results of your testing

**Comment by NordicGamerFE** [comment]
Confirmed working 0.2.9b
