### ISSUE TITLE
Pre-release 0.2.9d runs terrible

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#24]
After going from c to d the server runs terrible and even crashes
[Tick 10594]['Sir. Meow A Lot' depth=7 (16164..16170) ping=42ms] CQ bloat: removed 140, max: 4, 6 ticks this frame
165.609375 UNEXPECTED LONG FRAME DETECTED: 345.90ms elapsed, 565.73ms sim time, 6 ticks, 10594..10599.
 345.68ms Server Simulation
   6.31ms Server Game
   5.11ms Server Animation
   0.80ms UserCommands
   0.49ms Unaccounted
   0.15ms Server Send Networking

**Comment by rcnoob** [comment]
please enable debug mode, and let me know if you are using postgres or mysql. postgres is VERY early development so i expect to find bugs with it

**Comment by NordicGamerFE** [comment]
I was able to find out what it was if you spam jump in spawn it causes the issue

**Comment by NordicGamerFE** [comment]
Zone jumping disabled
![image](https://github.com/Letaryat/poor-sharptimer/assets/18188155/0c02ae98-69b4-4835-89aa-caf3469a882e)
Zone jumping enabled
![image](https://github.com/Letaryat/poor-sharptimer/assets/18188155/4fc34f98-4be0-40d0-9028-a14f5789e3df)

**Comment by rcnoob** [comment]
try now with 0.2.9e, thank you for testing :)

**Comment by NordicGamerFE** [comment]
fixed

**Comment by NordicGamerFE** [comment]
I am seeing some higher cpu usage then before, and this is expect but maybe add a warning in the config that the option will come with a performance hit

**Comment by rcnoob** [comment]
Ideally I am going to work on this more and find a way to completely disable the jump input, that way the command is not called over and over by jumping the small height it allows

**Comment by NordicGamerFE** [comment]
Fair enough. Do you need a testing server?

**Comment by rcnoob** [comment]
No I have a dedicated for all my servers + dev server, thank you though :)
