### ISSUE TITLE
SharpTimerModelSetter

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#27]
[SharpTimerModelSetter](https://github.com/DEAFPS/SharpTimerModelSetter/) links to nothing now

**Comment by Letaryat** [comment]
Hey!
Thanks for noticing that! It has been fixed and also I have added rampbugfix to the recommended dependencies.

We really recommend joining Sharptimer discord server where you could find many useful plugins and information about poor-sharptimer project like plugin recommendations. 

Anyway, thanks for letting us know. It has been fixed.
