### ISSUE TITLE
!reloadzones

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#30]
Adding !reloadzones would make it easier to edit zones

**Comment by rcnoob** [comment]
what would the use-case be for this? when the zones are automatically reloaded upon saving

**Comment by NordicGamerFE** [comment]
use case would be when editing the files directly to get the zones to perfectly line up with stuff or find a perfect height

**Comment by rcnoob** [comment]
added in 0.2.9 full-release
