### ISSUE TITLE
Option to not force disable sv_cheats

### ISSUE THREAD

**Issue by femboyfin** [Letaryat/poor-sharptimer#68]
Sometimes (e.g. on a private server), it's preferred to have sv_cheats on. The plugin forcing it off doesn't seem to be documented anywhere and isn't functionality most people are probably expecting, it'd be nice to have a convar to disable this.

**Comment by exkludera** [comment]
or just remove it
https://github.com/Letaryat/poor-sharptimer/blob/90193a1ecc9074263f2c83668150310e8f20f3f3/src/Plugin/Utils.cs#L797-L798

and put sv_cheats 0 in MapExecs cfgs instead

**Comment by exkludera** [comment]
fixed in [v0.3.0q](https://github.com/Letaryat/poor-sharptimer/releases/tag/v0.3.0q)
