### ISSUE TITLE
[suggestion] make bot visable to all

### ISSUE THREAD

**Issue by NordicGamerFE** [Letaryat/poor-sharptimer#70]
I would like if there was a config option to make the replay bot visable to all players

**Comment by M-archand** [comment]
Feature was added in [0.3.0](https://github.com/Letaryat/poor-sharptimer/releases/tag/v0.3.0). STFixes is required to use it.

**Comment by NordicGamerFE** [comment]
no it was not replay bot is only visable if you spectate it last time i checked.
