### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by AciidRaiin1** [Letaryat/poor-sharptimer#74]
00:12:04 [INFO] (plugin:SharpTimer) [SharpTimer] Loading Plugin...
00:12:04 [INFO] (plugin:SharpTimer) [SharpTimerDebug] Set gameDir to C:\Users\tyler\OneDrive\Desktop\CS2 SERVER\servers\1\serverfiles\game
00:12:04 [INFO] (plugin:SharpTimer) [SharpTimerDebug] Set mySQLpath to C:\Users\tyler\OneDrive\Desktop\CS2 SERVER\servers\1\serverfiles\game/csgo/cfg\SharpTimer/mysqlConfig.json
00:12:04 [EROR] (cssharp:PluginManager) Failed to load plugin from C:\Users\tyler\OneDrive\Desktop\CS2 SERVER\servers\1\serverfiles\game\csgo\addons\counterstrikesharp\plugins\SharpTimer\SharpTimer.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer

**Comment by rcnoob** [comment]
make sure you have styles disabled; in future updates windows cannot use style no matter the configuration. windows does not like the methodology used to enforce styles

**Comment by M-archand** [comment]
Closing issue as Windows no longer supports styles.
