### ISSUE TITLE
Custom Record Sounds

### ISSUE THREAD

**Issue by rveee** [Letaryat/poor-sharptimer#76]
Are you able to put custom sounds in the plugin right now or can you make it a feature in the future?

ps. if possible can you fix low gravity being reset to normal after using a ladder

**Comment by exkludera** [comment]
changing sounds can be done in pre-release [v0.3.0e](https://github.com/Letaryat/poor-sharptimer/releases/tag/v0.3.0e) and above

**Comment by rveee** [comment]
@exkludera how do I add my own sounds? I've tried but can't get it to work

**Comment by M-archand** [comment]
Feature works as of [0.3.0](https://github.com/Letaryat/poor-sharptimer/releases/tag/v0.3.0) stable.
