### ISSUE TITLE
Custom TOP ranks

### ISSUE THREAD

**Issue by yesyesno0** [Letaryat/poor-sharptimer#77]
Is there a way to make a top 10 ranks after god?

So every rank after god got a different rank and its depending on players rank on the server and not percentage.

Example the person thats rank 7 on the server got the rank "Legend" and its only rank 7 that can have it.

Thanks :D

**Comment by exkludera** [comment]
not possible with how it works right now😿
I guess we should make it fully customizable, but if/when that happens is another question

<img src="https://cdn.discordapp.com/emojis/1218823786959208488.webp?size=96&quality=lossless">
