### ISSUE TITLE
Sr Sounds

### ISSUE THREAD

**Issue by yesyesno0** [Letaryat/poor-sharptimer#84]
How do I add a custom mp3  sound to my SR tried with .wav aswell but can't get it to work.
Saw that you could change the sounds in a version but I have it but can't get it to work.

**Comment by M-archand** [comment]
Are you using [MultiAddonManager](https://github.com/Source2ZE/MultiAddonManager) and adding custom workshop assets for the sounds?

**Comment by yesyesno0** [comment]
Yes I have

**Comment by jke-cs** [comment]
sounds for me also not playing not even the default (0.3.0q), works with previous

**Comment by rveee** [comment]
Same for me and I also use MultiAddonManager

Tried adding the sound like this sounds/WrSound.vsnd

**Comment by exkludera** [comment]
it could be that you guys have sound disabled, try !sounds
when I first added sounds I made it play for everyone regardless if the player had it on or off, it got removed in [v0.3.0e](https://github.com/Letaryat/poor-sharptimer/releases/tag/v0.3.0e)
also sound was disabled by default before, but it got enabled in the same update

**Comment by M-archand** [comment]
Feature works as of [0.3.0](https://github.com/Letaryat/poor-sharptimer/releases/tag/v0.3.0) stable.
